### ISSUE TITLE
Feature request: Trigger notifications when multiple indicators are hot

### ISSUE THREAD

**Issue by decharel** [CryptoSignal/crypto-signal#293]
Feature request: 

Trigger notifications only when multiple indicators/informants are hot

**Comment by shads2** [comment]
This is something I would like to add

**Comment by december-soul** [comment]
to be a little clearer.

there are new hot indicators (which have become hot in the last time unit) and existing hot indicators. (which were already hot before)

for example:
sma and ema are already hot.
momentum becomes hot several time units later.

What do we want:

inform me if more than one indicator gets hot in a time unit
or do you want to be informed when one gets hot and several are already hot?

I think it makes a difference.

I would then suggest something like that as a parameter.

alert_min_hot: 1
alert_min_new_hot: 1
alert_min_cold: 1
alert_min_new_cold: 1

when all is set to 1 it is the default behavior.

I would set it this way for me

alert_min_hot: 3
alert_min_new_hot: 1
alert_min_cold: 3
alert_min_new_cold: 1

**Comment by december-soul** [comment]
maybe it would make sense to make a way like crossover with which you can link several signals.

combine will trigger only if all signals are hot

additional will trigger only if base_signal becomes hot and additional_signal are also hot
```
alert:
    std_combine:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signals:
              - sma
              - momentum
    std_additional:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          base_signal:
              - sma
          additional_signals:
              - sma
              - momentum

```

**Comment by december-soul** [comment]
I made some changes in my fork.
can you take a look?
https://github.com/december-soul/crypto-signal/commit/3a66cccf1efe00593bae843dc2ffe70296188ec7  (ignore stdout notifiers)
and
https://github.com/december-soul/crypto-signal/commit/8c84740bad444bf258994f82dc168df49fc16c60

you have two new keywords for message templates
`template: "[hot:{{hot_count}} cold:{{cold_count}}] ..."`

and a new section in the config file
```
notifiers:
    general:
        min_hot: 3
        min_cold: 4
```
default is 1 (old behaviour)
