### ISSUE TITLE
Can not get `rsi` alert when it is hot

### ISSUE THREAD

**Issue by Limon-O-O** [CryptoSignal/crypto-signal#302]
```
settings:
    update_interval: 5
    market_pairs:
        - ADA/BTC
exchanges:
    binance:
        required:
            enabled: true

    bittrex:
        required:
            enabled: false 

indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 50
      cold: 70
      candle_period: 4h
      period_count: 15
          
notifiers:
    discord:
        required:
            webhook: https://discordapp.com/api/webhooks
            username: CryptoSignal2
        optional:
            avatar: https://bitcoin.org/img/icons/opengraph.png
            template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}} - {{market}} - {{indicator}} - {{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}"

```
