### ISSUE TITLE
Current Price on output and notification

### ISSUE THREAD

**Issue by sacharya** [CryptoSignal/crypto-signal#326]
Would be nice to have the current price as an output and on notification.

**Comment by december-soul** [comment]
works
take a look at
OHLCV - open, high, low, close, volume




this config.yam

```
settings:
  update_interval: 300
  log_level: INFO
  market_pairs:
    - BTC/USDT

exchanges:
  bittrex:
    required:
      enabled: true

notifiers:
    stdout:
        required:
            enable: true
        optional:
            template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{market}} {{indicator}} is {{status}}! ({{values}}){{ '\n' -}}"

indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once_
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1h
      period_count: 14

informants:
  ohlcv:
    - enabled: true
      signal:
        - close
      candle_period: 1h
      period_count: 15
```

will produce this output.

```enabled notifers: ['stdout']
Starting default analyzer...
Found configured markets: ['BTC/USDT']
Using the following exchange(s): ['bittrex']
Beginning analysis of bittrex
Beginning analysis of BTC/USDT
BTC/USDT:

indicators:     momentum #0: -813.85999999      macd #0: -109.09987122  ichimoku #0: 6769.68877874/7188.44450000        stoch_rsi #0: 38.97333058       mfi #0: 30.50138543     obv #0: -8267.12218905  rsi #0: 65.12944315 
crossovers:
informants:     ohlcv #0: 6566.00000000         ema #0: 6557.06267743   bollinger_bands #0: 7491.31229247/6748.58487656/6005.85746066   vwap #0: 6752.35402775  sma #0: 6676.96716053 


Sleeping for 300 seconds```

**ohlcv #0: 6566.00000000** is the current close price
