### ISSUE TITLE
Dosent post on Telegram Channel

### ISSUE THREAD

**Issue by bottest123** [CryptoSignal/crypto-signal#329]
I have added my telegram channel ID and my bot I'd in config.yml 
And even my bot is admin in channel why dosent it post in my channel?

Help please
It shows like this 

![screenshot_2018-10-15-17-39-57-231](https://user-images.githubusercontent.com/41206183/46950147-63f34700-d0a1-11e8-9836-1e489f3447f0.jpeg)

But dosent post on telegram channel 

Help please

**Comment by laliux** [comment]
@bottest123 

I don't know what means "channel id".

For Telegram notifications you need to create a bot and then get an api token.

My token and chat_id into config.yml looks like this:

token: 662318103:AAHOchZ3Egq2clOC88GEqnUSHxxxxxxxxx
chat_id: 20739000

Best

**Comment by minerlab** [comment]
to know the chat id just invite @RawDataBot and look at the chat section. the result will be similar to this
"message": {
    "chat": {
        "id": -210987654,
        "title": ...,
        "type": "group",
        ...

in config.yml put bot token and id chat and work

**Comment by aimanbaharum** [comment]
I have the same issue. I've managed to get the token for my bot and the chat_id of my test group. I invited the bot into the group as well.

Ran the docker in a Ubuntu 19.04 VM, analysis runs fine. But somehow the bot doesn't post the update to the telegram group. Is it because I'm running it in a VM?

config.yml:

```
notifiers:
    telegram:
        required:
            token: 726148:AAG[REDACTED]4f-2CCc
            chat_id: -378006
        optional:
            parse_mode: html
            template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}" 
```

Found the chat_id via `https://api.telegram.org/bot<BOT_TOKEN>/getUpdates` API call:

```
{
  "chat": {
    "id": -378006,
    "title": "test signal bot",
    "type": "group",
    "all_members_are_administrators": true
  }
}
```

What did I do wrong?
