### ISSUE TITLE
Right notification, but posted the wrong chart on Telegram

### ISSUE THREAD

**Issue by heartsmith** [CryptoSignal/crypto-signal#348]
Hi,
I ran the codes for a few days to try the chart feature, with ichimoku indicator running on all pairs on Binance. The notifications worked well, but I got the wrong charts most of the time.

For example, the hot notification below was for VET/USDT(hot), but the chart posted was for CVC/BTC(cold), which had nothing to do with the notification. 

![Screenshot_20190512-122504_Telegram](https://user-images.githubusercontent.com/32376497/57705688-779c7580-76a3-11e9-99e3-9c6d92eaa73c.jpg)

Below is the config.yml used (without the notifiers section):
```
settings:
  log_mode: standard
  log_level: INFO
  output_mode: cli
  enable_charts: true
  update_interval: 10      

exchanges:
    binance:
        required:
            enabled: true
        all_pairs:
            - BTC
            - USDT
indicators:
    ichimoku:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - leading_span_a
            - leading_span_b
          hot: true
          cold: true
          candle_period: 2h
          mute_cold: true
```

thank you for the hard and brilliant work! :D
