### ISSUE TITLE
Exception "telegram.error.RetryAfter"

### ISSUE THREAD

**Issue by w1ld3r** [CryptoSignal/Crypto-Signal#382]
Need to add in `telegram_client.py` a retry for the exception of type `telegram.error.RetryAfter`.

**Comment by x1n5h3n** [comment]
Or a sleep between each `send_message` ?

**Comment by laliux** [comment]
Hey @x1n5h3n ,..

I need to see your config file to try to reproduce the error.

**Comment by x1n5h3n** [comment]
```yml
settings:
  log_level: INFO
  update_interval: 10

exchanges:
  kraken:
    required:
      enabled: true
    all_pairs:
      - EUR
    exclude:
      - XBTEUR.d
      - ETHEUR.d
      - USDC
      - USDT
      - MLN

indicators:
  rsi:
    - enabled: false
      alert_enabled: false
  momentum:
    - enabled: false
      alert_enabled: false
  mfi:
    - enabled: false
      alert_enabled: false
  obv:
    - enabled: false
      alert_enabled: false
  stoch_rsi:
    - enabled: false
      alert_enabled: false
  macd:
    - enabled: false
      alert_enabled: false
  ichimoku:
    - enabled: true
      alert_enabled: false
      signal:
        - leading_span_a
      candle_period: 1d
    - enabled: true
      alert_enabled: false
      signal:
        - leading_span_b
      candle_period: 1d
  iiv:
    - enabled: false
      alert_enabled: false

informants:
    lrsi:
        - enabled: false
    vwap:
        - enabled: false
    sma:
        - enabled: false
    ema:
        - enabled: true
          alert_enabled: false
          signal:
            - ema
          candle_period: 1d
          period_count: 9
        - enabled: true
          alert_enabled: false
          signal:
            - ema
          candle_period: 1d
          period_count: 26
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: false

crossovers:
    std_crossover:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          key_indicator: ichimoku
          key_indicator_index: 0
          key_indicator_type: indicators
          key_signal: leading_span_a
          crossed_indicator: ichimoku
          crossed_indicator_index: 1
          crossed_indicator_type: indicators
          crossed_signal: leading_span_b
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          key_indicator: ema
          key_indicator_index: 0
          key_indicator_type: informants
          key_signal: ema
          crossed_indicator: ema
          crossed_indicator_index: 1
          crossed_indicator_type: informants
          crossed_signal: ema

notifiers:
    telegram:
        required:
            token: 1337
            chat_id: 1337
        optional:
            parse_mode: html
            template: "[{{market}}] {{analysis.config.candle_period}} is {{status}} ({{values}}){{ '\n' -}}"
```
