### ISSUE TITLE
Stoch RSI results are wrong

### ISSUE THREAD

**Issue by bluetyphoon77** [CryptoSignal/Crypto-Signal#409]
Is there a way to set the 4 parameters we set in Tradingview ? K, D, RSI length, Stochastic length ?
To be sure to have the accurate results ?
Thanks a lot

**Comment by laliux** [comment]
No,.. there is no way.. for StochRSI you only can adjust the RSI length.

:|

**Comment by bluetyphoon77** [comment]
I've set it to get the 3 results ... stoch K and D
All are wrong results.... when I check on Tradingview.
I see you are using STOCHRSI... why ? Since results are not accurate ?

**Comment by laliux** [comment]
Read the FAQ -> https://github.com/CryptoSignal/Crypto-Signal

Btw, I don't use it and I don't know how accurate it is, but when I have a little time I will review what you say.

**Comment by laliux** [comment]
@bluetyphoon77 

I tested StochRSI and it is working as expected. I'm using this config to get Buy signals for 4h candles. Repeat, it is working.

``` 
  stoch_rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - stoch_rsi
      hot: 20
      cold: 80
      candle_period: 4h
      period_count: 14
      hot_label: 'Possible Uptrend is coming'
      cold_label: 'Possible Downtred is coming'
      indicator_label: '#StochRSI'
      mute_cold: true 
```

I don't know why you say it gives wrong results.

:/

**Comment by bluetyphoon77** [comment]
Because when I use it on a daily in my case, I get wrong values.

When I check on Tradingview and compare, it is totally different. I would not bother here before testing first.

So what do you mean by "it is working" ? To grab data ? yes I get data. But NOT accurate at all.

How do you know your results are accurate ? what is your way to verify ?


________________________________

**Comment by bluetyphoon77** [comment]
And where did you set stoch/length/k/d settings ?

________________________________

**Comment by laliux** [comment]
```
  stoch_rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - stoch_rsi
      hot: 20
      cold: 80
      candle_period: 1d
      period_count: 14
      hot_label: '--Possible Uptrend is coming'
      cold_label: '--Possible Downtred is coming'
      indicator_label: 'StochRSI 1D'
      mute_cold: true  
```
Running this config with 1d candles I get buy signals for XLM/USDT , ZEC/USDT, LINK/USDT and many more (right now).

Works -> I receive this signals in my Telegram channel.
Verify -> I check Stoch RSI chart indicator in Binance(TradingView) and it is correct, I see buy signals.

The only value that you can configure here is **period_count: 14** . In fact it is the standard value for RSI & StochRSI.

**Comment by laliux** [comment]
BTW, Binance/TradingView **doesnt** plot original STOCH_RSI line, just smoothK and smoothD.

The code in this program doesnt use config values for K and D because it works with original stoch_rsi not with smoothed K, D values.

**period_count = 14**  =>  rsi_length = 14 , stoch_rsi_length = 14

**Comment by bluetyphoon77** [comment]
Thanks for your answer eduardo.

I've RE-tested with some other pairs a few minutes ago

This is what I get when I use the code you sent me NOW on the 6/12/2020, at 14:23 UTC+1 (PAris time)


Beginning analysis of LINK/USDT
LINK/USDT:
indicators:     stoch_rsi #0: 6.19683765

HBAR/USDT:
indicators:     stoch_rsi #0: 41.81868073

DGB/BTC:
indicators:     stoch_rsi #0: 19.01127194

VIA/BTC:
indicators:     stoch_rsi #0: 49.36108561

POWR/BTC:
indicators:     stoch_rsi #0: 34.24612329


When I check on binance or tradingview at the same moment I have
(for a stochrsi of k=3, d=4, length 14, stoch 14)

LINK: 7.22 for K/16.92 for D
HBAR: 31.31/58.82
DGB: 2.72/27.01
VIA: 36.94/52.39
POWR: 17.86/49.47

SO, you can see, totally wrong values !

Maybe you should test with these ones and send me your results.





________________________________

**Comment by laliux** [comment]
I think I finally understood your point,..

Change the "**signal**" value in your config file, set:

```
  stoch_rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - slow_k
        - slow_d
      hot: 20
      cold: 80
......
```
The output you will see is for K/D respectively.
