### ISSUE TITLE
EMA option

### ISSUE THREAD

**Issue by flamby69** [CryptoSignal/Crypto-Signal#436]
Hi,

I follow the Wiki to setup my EMAs. I see there is this parameter : candle_period: 1d
witch is good, but i'd like to know if it is possible to have the ema of the Highs, or the ema of the Lows as an option, instead of the EMA of the candle that seems to be the EMA of the Close of that candle.
Thanks by advance.

**Comment by flamby69** [comment]
Hi, 

Thanks for taking time answering me. I used to do some expert advisor using metatrader some years ago. I had good result drawing EMA (exponential )or SMA (simple moving average ) of the Low or High of the prices. i use it for example like this : ((Close[0]<EMA_Low && Close[1]>EMA_Low)) then i send Sell order. Where Close[0] is the actual Close, and Close[1] is the Close before this one. 
I understand that  i might send too many notifications if it don't wait the close to send the notification, i use it filtering the signal to have only accurate notification. But it would be awesome if this could be do-able in crypto-signal.

**Comment by Alorse** [comment]
I'm not sure if I can help you, but I have one more question.
Do you want this feature for some indicator or to use specifically where?

**Comment by flamby69** [comment]
It would be awesome if we can add it on the ma_crossover section, and do something like this : 

```
    ma_crossover:
        - enabled: true
          candle_period: 1h
          alert_enabled: true
          alert_frequency: once
          exponential: true
          ma_fast: 50
          ma_slow: 100
          ma_fast_calculation: Price_Low
          ma_slow_calculation: Price_Close
          signal:
            - open
            - close
          hot_label: 'Uptrend is coming'
          cold_label: 'Downtred is coming'
          indicator_label: 'EMA 50/100 Cross'
```
But, maybe it will be even more powerfull if we can have the ema, or sma of whatever we want : price_low, price_open, price_close, or price_high

Don't hesitate if you have other question. my goal with this is to filter signal and make sell order only when price is under one sma of the LOWs, and buy order only when price is upper the sma of the HIGHs.
