### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by chanever** [CryptoSignal/Crypto-Signal#470]
Hello. I installed crpyto signal and i have a problem when i m running.

I followed a guide that is in github page. and i want to show my problem.
![image](https://user-images.githubusercontent.com/54233034/235446463-787817e6-d341-4d7e-9a5d-f3d4b04dc8f6.png)

this is a picture when i run docker. (when i run this program)

and i put config.yml in this path.
![image](https://user-images.githubusercontent.com/54233034/235446563-ef83d4f5-0b72-4a67-91cc-9e1845f0e8dc.png)

and i copied a config.yml example code and changed telegram token and chat id. and Docker is installed.

i want to know everytime i run this program, this program couldn't find enabled notifiers, exchange etc.. (if you see my first picture.)

i think this is my config.yml problem but i can't find what is wrong. 
```
settings:
    log_level: INFO
    update_interval: 180
    market_pairs:
        - BTC/USDT
        - ETH/USDT
        - SOL/USDT
        - RLC/USDT
        - INJ/USDT
        - CTSI/USDT
        - RNDR/USDT

exchanges:
    huobipro:
        required:
            enabled: true
    binance:
        required:
            enabled: true

indicators:
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1h
          period_count: 10
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 5m
          period_count: 10
    stoch_rsi:
        - enabled: false
          alert_enabled: true
          alert_frequency: once
          signal:
            - stoch_rsi
          hot: 20
          cold: 80
          candle_period: 5m
          period_count: 14
    momentum:
        - enabled: false
          alert_enabled: false
          alert_frequency: once
          signal:
            - momentum
          hot: 0
          cold: 0
          candle_period: 1d
          period_count: 10
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - momentum
          hot: 0
          cold: 0
          candle_period: 1h
          period_count: 12
    macd:
        - enabled: false
          alert_enabled: false
          alert_frequency: once
          signal:
            - macd
          hot: 0
          cold: 0
          candle_period: 15m
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - macdsignal
          hot: 0
          cold: 0
          candle_period: 15m
    obv:
        - enabled: false
    mfi:
        - enabled: false
          alert_enabled: true
          alert_frequency: once
          signal:
            - mfi
          hot: 20
          cold: 80
          candle_period: 5m
          period_count: 14
    ichimoku:
        - enabled: false

informants:
    ema:
        - enabled: false
          signal:
            - ema
          candle_period: 1d
          period_count: 10
        - enabled: true
          signal:
            - ema
          candle_period: 1d
          period_count: 30

crossovers:
    std_crossover:
        - enabled: false
          alert_enabled: true
          alert_frequency: once
          key_indicator: ema
          key_indicator_index: 0
          key_indicator_type: informants
          key_signal: ema
          crossed_indicator: ema
          crossed_indicator_index: 1
          crossed_indicator_type: informants
          crossed_signal: ema
        - enabled: false
          alert_enabled: true
          alert_frequency: once
          key_indicator: macd
          key_indicator_index: 0
          key_indicator_type: indicators
          key_signal: macd
          crossed_indicator: macd
          crossed_indicator_index: 1
          crossed_indicator_type: indicators
          crossed_signal: macdsignal

notifiers:
    telegram:
        required:
            token: "i wrote token from here and erase it just in case"
            chat_id: "i wrote chat_id from here and erase it just in case"
        optional:
            parse_mode: html
            template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}" 
``` 

this is my config.yml code too. i upload it just in case.
im really thank you for helping me.
